[project]
project_id = "mcqcmrcipdqkxrrrqltw"

[auth]
enabled = true
site_url = "localhost"

[functions]
enable_warnings = true

[functions.mark-attendance]
verify_jwt = true

[functions.generate-monthly-report]
verify_jwt = true
